[package]
name = "arpa-contract-client"
description = "ARPA contract client library"

version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
exclude.workspace = true

[dependencies]
dkg-core.workspace = true
threshold-bls.workspace = true
arpa-core.workspace = true

futures-util = "0.3"
tokio = { version = "1.37.0", features = ["full"] }
thiserror = "1.0.15"
anyhow = "1.0.31"
serde = "1.0.106"
log = "0.4"
async-trait = "0.1.35"
bincode = "1.2.1"
tonic = "0.14"
prost = "0.14"
alloy = { workspace = true, features = ["full", "json"] }
rustc-hex = "2.1.0"
tokio-retry = "0.3"
rand = "0.8"

[lib]
name = "arpa_contract_client"
path = "src/lib.rs"

[dev-dependencies]
simple_logger = "4.2.0"
alloy = { workspace = true, features = ["full", "json", "provider-anvil-node"] }
