[package]
name = "arpa-node"
authors = ["kafeikui"]
description = "This crate provides a set of tools on the node side of the ARPA BLS Threshold Signature Scheme (BLS-TSS) Network, including Threshold-BLS based on-chain randomness service(Randcast)."

version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
exclude.workspace = true

[[bin]]
name = "node-client"
path = "src/node_client.rs"

[[bin]]
name = "node-shell"
path = "src/node_shell.rs"

[[bin]]
name = "node-config-checker"
path = "src/node_config_checker.rs"

[build-dependencies]
tonic-prost-build = "0.14"
serde_json = "1.0"

[dependencies]
arpa-log.workspace = true
arpa-core.workspace = true
arpa-dal.workspace = true
arpa-sqlite-db.workspace = true
arpa-contract-client.workspace = true
dkg-core.workspace = true
threshold-bls.workspace = true

gumdrop = "0.7.0"
rand = "0.8"
bincode = "1.2.1"
glob = "0.3.0"
serde = "1.0.106"
thiserror = "1.0.15"
serde_json = "1.0.53"
hex = "0.4.2"
anyhow = "1.0.31"
futures = "0.3.5"
async-trait = "0.1.35"
tokio = { version = "1.37.0", features = ["full"] }
rustc-hex = "2.1.0"
tonic = "0.14"
tonic-health = "0.14"
prost = "0.14"
tonic-prost = "0.14"
serde_yaml = "0.8"
tokio-retry = "0.3"
log = "0.4"
log4rs = "1.2.0"
log-mdc = "0.1.0"
chrono = "0.4"
structopt = "0.3"
alloy = { workspace = true, features = ["full"] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
tower = "0.5"
hyper = "1.7"
reedline-repl-rs = { version = "1.0.6", features = ["async"] }
actix-web = "4"
check-latest = { version = "1.0.2", default-features = false, features = [
    "async",
] }

[dev-dependencies]
alloy = { workspace = true, features = ["full", "provider-anvil-node"] }
arpa-node = { path = ".", features = [] }  
regex = "1.11.1" 
