node_advertised_committer_rpc_endpoint: "172.17.0.1:50061"

node_committer_rpc_endpoint: "0.0.0.0:50061"

node_management_rpc_endpoint: "0.0.0.0:50091"

node_management_rpc_token: "for_test"

provider_endpoint: "ws://172.17.0.1:8546"

chain_id: 900

controller_address: "0x967AB65ef14c58bD4DcfFeaAA1ADb40a022140E5"

controller_relayer_address: "0x547382C0D1b23f707918D3c83A77317B71Aa8470"

adapter_address: "0x8e264821AFa98DD104eEcfcfa7FD9f8D8B320adA"

data_path: "./db/data1.sqlite"

logger:
  node_id: 1
  context_logging: false
  log_file_path: log/1/
  rolling_file_size: 10 gb

account:
  private_key: f214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897

listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 1000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  block_time: 3
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 1000
  dkg_wait_for_phase_interval_millis: 1000
  provider_polling_interval_millis: 1000
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

relayed_chains:
  - chain_id: 901
    description: "OP"
    provider_endpoint: "ws://172.17.0.1:9546"
    controller_oracle_address: "0x0ed64d01D0B4B655E410EF1441dD677B695639E7"
    adapter_address: "0x40a42Baf86Fc821f972Ad2aC878729063CeEF403"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 3
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false
