//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub index: i32,
    pub epoch: i32,
    pub size: i32,
    pub threshold: i32,
    pub state: i32,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub public_key: Option<Vec<u8>>,
    pub members: String,
    pub committers: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub share: Option<Vec<u8>>,
    pub dkg_status: i32,
    pub self_member_index: i32,
    pub dkg_start_block_height: i32,
    pub create_at: String,
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
