[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 300
ignored_error_codes = [5159, 5574]
solc = "0.8.18"
fs_permissions = [{ access = "read-write", path = "./" }]

# Use this to verify contracts on etherscan
# libraries = ["src/libraries/BLS.sol:BLS:0x0fd3ef730b4816d882dd8906348c98898d3d8a75", "src/libraries/GroupLib.sol:GroupLib:0xb029a3dcda100324b5d252c9d3c36110eed7c3ca"]
# libraries = [
#     "src/libraries/BLS.sol:BLS:0xda08c1be1519c3adf6a71b4b0634208e02eccdc9",
# ]
# libraries = [
#     "src/libraries/BLS.sol:BLS:0xda08c1be1519c3adf6a71b4b0634208e02eccdc9",
#     "src/libraries/ChainHelper.sol:ChainHelper:0x3bA2dbD7466919affea5Fe34cc642d7d669eF6aa",
# ]

[profile.test]
verbosity = 2
gas_price = 1000000000

[profile.ci]
