[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 300
ignored_error_codes = [5159, 5574]
solc = "0.8.18"

[profile.test]
verbosity = 2
gas_price = 1000000000

[profile.ci]
# Use this to verify contracts on etherscan
# libraries = ["src/libraries/BLS.sol:BLS:0x0fd3ef730b4816d882dd8906348c98898d3d8a75", "src/libraries/GroupLib.sol:GroupLib:0xb029a3dcda100324b5d252c9d3c36110eed7c3ca"]
# libraries = ["src/libraries/BLS.sol:BLS:0xCCefBB9bC55b08cca17713DE3456fe526352d89E"]
