node_committer_rpc_endpoint: "[::1]:50060"

node_management_rpc_endpoint: "[::1]:50099"

node_management_rpc_token: "for_test"

provider_endpoint: "localhost:8545"

controller_address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"

data_path: "data1.sqlite"

account:
  private_key: "4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318"
  # keystore:
  #   password: env
  #   path: test.keystore

# listeners:
#   - Block
#   - NewRandomnessTask

context_logging: true
