node_committer_rpc_endpoint: "[::1]:50065"

node_management_rpc_endpoint: "[::1]:50095"

node_management_rpc_token: "for_test"

provider_endpoint: "http://127.0.0.1:8545"

chain_id: 31337

controller_address: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707"

adapter_address: "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6"

data_path: "./data5.sqlite"

account:
  private_key: "c526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa"

listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 1000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 1000
  dkg_wait_for_phase_interval_millis: 1000
  provider_polling_interval_millis: 1000
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

context_logging: false

node_id: 5
