node_committer_rpc_endpoint: "[::1]:50060"

node_management_rpc_endpoint: "[::1]:50099"

node_management_rpc_token: "for_test"

provider_endpoint: "localhost:8545"

chain_id: 0

controller_address: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707"

adapter_address: "0x0165878a594ca255338adfa4d48449f69242eb8f"

data_path: "./data.sqlite"

account:
  private_key: "4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318"
  # keystore:
  #   password: env
  #   path: test.keystore

listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 10000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 10000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 10000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 10000
  dkg_wait_for_phase_interval_millis: 10000
  provider_polling_interval_millis: 10000
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

context_logging: true

node_id: 0
