node_committer_rpc_endpoint: "[::1]:50062"

node_management_rpc_endpoint: "[::1]:50092"

node_management_rpc_token: "for_test"

provider_endpoint: "http://127.0.0.1:8545"

chain_id: 31337

controller_address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"

data_path: "./data2.sqlite"

account:
  private_key: "dbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"

context_logging: false
