node_committer_rpc_endpoint: "[::1]:50060"

node_management_rpc_endpoint: "[::1]:50099"

node_management_rpc_token: "for_test"

provider_endpoint: "localhost:8545"

chain_id: 0

controller_address: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707"

adapter_address: "0x0165878a594ca255338adfa4d48449f69242eb8f"

data_path: "./data.sqlite"

account:
  private_key: "4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318"
  # keystore:
  #   password: env
  #   path: test.keystore

# listeners:
#   - Block
#   - NewRandomnessTask

context_logging: true

node_id: 0
