//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "node_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub id_address: String,
    pub node_rpc_endpoint: String,
    pub dkg_private_key: Vec<u8>,
    pub dkg_public_key: Vec<u8>,
    pub create_at: String,
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
