node_committer_rpc_endpoint: "0.0.0.0:50061"

node_advertised_committer_rpc_endpoint: "<EXTERNAL_IP>:50061"

node_management_rpc_endpoint: "0.0.0.0:50091"

node_management_rpc_token: "<CHANGE_ME>"

node_statistics_http_endpoint: "0.0.0.0:50081"

provider_endpoint: "<ETH_MAINNET_RPC_WEBSOCKET_ENDPOINT>"

chain_id: 1

is_eigenlayer: true

controller_address: "0xBcA1a9cA6B460E6B265DBcf7249b45BDdC381Dfd"

adapter_address: "0x4363154E1eC107F81239A4F0b1CB3AB5161129Ca"

controller_relayer_address: "0xF098A30c21dF6Bc1aED15e172001E4675131aD4A"

account:
  keystore:
    password: <KEYSTORE_PASSWORD_OF_NODE_ACCOUNT>
    path: node.keystore

logger:
  context_logging: false
  rolling_file_size: 10 gb
  
listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 10000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 10000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 10000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  block_time: 12
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 10000
  dkg_wait_for_phase_interval_millis: 10000
  provider_polling_interval_millis: 10000
  provider_reset_descriptor:
    interval_millis: 5000
    max_attempts: 17280
    use_jitter: false
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

relayed_chains:
  - chain_id: 10
    description: "OP"
    provider_endpoint: "<OP_MAINNET_RPC_WEBSOCKET_ENDPOINT>"
    controller_oracle_address: "0x1e207b98a987AaD2A3443BD79d56faff4F11bfDf"
    adapter_address: "0xB4451B6EDaA244a7Ea2D47D14327121709B0a6F6"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 2
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false
  - chain_id: 8453
    description: "Base"
    provider_endpoint: "<BASE_MAINNET_RPC_WEBSOCKET_ENDPOINT>"
    controller_oracle_address: "0x5D7bb19fC0856f5bc74b66f2c7b0258c1aeafD7f"
    adapter_address: "0xDBa5dE33511b4b8549994d30E73b47fedc8cC2C2"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 2
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false
  - chain_id: 690
    description: "RedStone"
    provider_endpoint: "wss://rpc.redstonechain.com"
    controller_oracle_address: "0x1499803d9116d1112753f2d8bF3389245Ddce8b2"
    adapter_address: "0x5D7bb19fC0856f5bc74b66f2c7b0258c1aeafD7f"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 2
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false