ode_committer_rpc_endpoint: "0.0.0.0:50061"

node_advertised_committer_rpc_endpoint: "<EXTERNAL_IP>:50061"

node_management_rpc_endpoint: "0.0.0.0:50091"

node_management_rpc_token: "<CHANGE_ME>"

node_statistics_http_endpoint: "0.0.0.0:50081"

provider_endpoint: "<ETH_HOLESKY_RPC_WEBSOCKET_ENDPOINT>"

chain_id: 17000

is_eigenlayer: true

controller_address: "0xbF53802722985b01c30C0C065738BcC776Ef5A69"

controller_relayer_address: "0x4A88f1d5D3ab086763df5967D7560148006eE8b4"

adapter_address: "0x88ab708e6A43eF8c7ab6a3f24B1F90f52a1682b8"

logger:
  context_logging: false
  rolling_file_size: 10 gb

account:
  private_key: "<YOUR_PRIVATE_KEY>"
  
listeners:
  - l_type: Block
    interval_millis: 0
    use_jitter: true
  - l_type: NewRandomnessTask
    interval_millis: 0
    use_jitter: true
  - l_type: PreGrouping
    interval_millis: 0
    use_jitter: true
  - l_type: PostCommitGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: PostGrouping
    interval_millis: 1000
    use_jitter: true
  - l_type: ReadyToHandleRandomnessTask
    interval_millis: 1000
    use_jitter: true
  - l_type: RandomnessSignatureAggregation
    interval_millis: 2000
    use_jitter: false

time_limits:
  block_time: 12
  dkg_timeout_duration: 40
  randomness_task_exclusive_window: 10
  listener_interval_millis: 1000
  dkg_wait_for_phase_interval_millis: 1000
  provider_polling_interval_millis: 1000
  provider_reset_descriptor:
    interval_millis: 5000
    max_attempts: 17280
    use_jitter: false
  contract_transaction_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 3
    use_jitter: true
  contract_view_retry_descriptor:
    base: 2
    factor: 500
    max_attempts: 5
    use_jitter: true
  commit_partial_signature_retry_descriptor:
    base: 2
    factor: 1000
    max_attempts: 5
    use_jitter: false

relayed_chains:
  - chain_id: 17069
    description: "Redstone Garnet"
    provider_endpoint: "wss://rpc.garnetchain.com"
    controller_oracle_address: "0x901105C43C7f0e421b33c9D1DaA25f54076F6563"
    adapter_address: "0x323488A9Ad7463081F109468B4E50a5084e91295"
    listeners:
      - l_type: Block
        interval_millis: 0
        use_jitter: true
      - l_type: NewRandomnessTask
        interval_millis: 0
        use_jitter: true
      - l_type: ReadyToHandleRandomnessTask
        interval_millis: 1000
        use_jitter: true
      - l_type: RandomnessSignatureAggregation
        interval_millis: 2000
        use_jitter: false
    time_limits:
      block_time: 2
      randomness_task_exclusive_window: 10
      listener_interval_millis: 1000
      provider_polling_interval_millis: 1000
      provider_reset_descriptor:
        interval_millis: 5000
        max_attempts: 17280
        use_jitter: false
      contract_transaction_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 3
        use_jitter: true
      contract_view_retry_descriptor:
        base: 2
        factor: 500
        max_attempts: 5
        use_jitter: true
      commit_partial_signature_retry_descriptor:
        base: 2
        factor: 1000
        max_attempts: 5
        use_jitter: false
