name: Contract Unit Tests On PR

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  contract-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --names
        id: build
        working-directory: contracts
      - name: Run Forge tests
        run: |
          forge test --gas-price 1000000000 -vvv
        id: test
        working-directory: contracts
