name: Lint On PR

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Format
        run: cargo fmt
      - name: Lint
        run: cargo clippy -- -A clippy::derive_partial_eq_without_eq
