name: scenario-test
on:
  push:
    pull_request:
jobs:
  scenario-test:
    runs-on: ubuntu-latest
    
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: test-branch
        
    - name: Pull Docker image
      run: docker pull andlyn/arpanetwork-test:latest

    - name: Run Docker container
      run: |
        docker run --name=scenario \
          --platform=linux/arm64/v8 \
          -v ${{ github.workspace }}:/BLS-TSS-Network \
          andlyn/arpanetwork-test:latest /bin/bash -c "cd /BLS-TSS-Network; robot ./"