name: scenario-test

on:
  pull_request_target:
jobs:
  scenario-test:
    runs-on: ubuntu-latest
    steps:     
    - name: Pull Docker image
      run: docker pull andlyn/arpanetwork-test:latest
  
    - name: Run Docker container
      run: |
        docker run --name=scenario \
          andlyn/arpanetwork-test:latest \
          /bin/bash -c "git clone https://github.com/ARPA-Network/BLS-TSS-Network.git; \
          cd BLS-TSS-Network; git checkout ${{ github.event.pull_request.head.sha }}; \
          robot ./"