name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y protobuf-compiler libprotobuf-dev pkg-config libssh-dev build-essential lsof findutils supervisor git net-tools python3 python3-pip make jq docker.io docker-compose && \
        python -m pip install --upgrade pip==22.3.1 && \
        pip install -r requirements.txt

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.20.0'

    - name: Clone Optimism
      run: git clone https://github.com/ethereum-optimism/optimism.git

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy

    - name: Install Foundry
      run: cargo install --git https://github.com/foundry-rs/foundry --profile local --locked forge cast anvil