name: scenario-test

on:
  pull_request:

jobs:
  scenario-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y protobuf-compiler libprotobuf-dev pkg-config libssh-dev build-essential lsof git net-tools make jq && \
          pip install -r requirements.txt
        working-directory: tests

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.20.0"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-05-14
          override: true
          components: rustfmt, clippy

      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559

      - name: Run Forge build
        run: |
          forge --version
          forge build --names
        id: build
        working-directory: contracts
      - name: Run Cargo build
        run: |
          cargo build

      - name: run tests
        run: |
          robot --include l1 tests/scenarios/
