name: Unit Tests On PR

on:
  pull_request_target:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-29
          override: true
          components: rustfmt, clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run tests
        run: CARGO_HTTP_MULTIPLEXING=false cargo test --all -- --test-threads=1 --nocapture
