name: Node Unit Tests On PR

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Node Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-7bef9caccfe62761225be66e84bea2810e656c96
      - name: Install Solc
        run: |
          curl -fsSL https://github.com/ethereum/solidity/releases/download/v0.8.27/solc-static-linux -o /usr/local/bin/solc
          chmod +x /usr/local/bin/solc
        shell: bash
      - name: Run all tests
        run: CARGO_HTTP_MULTIPLEXING=false cargo test --features unittest -- --test-threads=1 --nocapture
