name: Unit Tests On PR

on:
  pull_request_target:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Run tests
        run: cargo test --package randcast-node --lib -- --test-threads=1
